# Generated by Django 4.0.3 on 2022-03-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_delete',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bookcategory',
            name='status',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
