# Generated by Django 4.0.3 on 2022-04-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_book_is_delete_book_status_bookcategory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(error_messages={'required': 'Enter your first name'}, max_length=100)),
                ('last_name', models.CharField(error_messages={'required': 'Enter your last name'}, max_length=100)),
                ('email', models.EmailField(error_messages={'required': 'Enter your email'}, max_length=100)),
                ('password', models.CharField(error_messages={'required': 'Enter your password'}, max_length=100)),
                ('password2', models.CharField(max_length=100)),
                ('is_delete', models.CharField(default=False, max_length=100)),
                ('status', models.CharField(default=True, max_length=100)),
                ('uniqueid', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='file_url',
            field=models.FileField(blank=True, max_length=200, upload_to='documents'),
        ),
    ]
